### ISSUE TITLE
Initialize router stack on creation

### ISSUE THREAD

**Issue by derigible** [thetalecrafter/middle-router#71]
https://github.com/thetalecrafter/middle-router/blob/83a7437dcd706aaa9457e5a4133cfcf550669f51/lib/router.js#L32

When attempting to replace the url path before routing has occurred (useful in the case of an SPA that will redirect to an authentication page if no authorization token is found), this will cause the page to crash because it attempts to add the previous route to the stack which has not yet been initialized. This is most likely due to the fact that the router is not yet listening because the router has not been started. By initializing the stack on route creation it will forgo this error. Or, if there is a separate workaround for this, it should be documented.

**Comment by thetalecrafter** [comment]
Yeah, that error isn't very useful, but I'd argue that the case you run into it should still throw an error. There is a bunch of setup beyond creating that array that takes place when you start listening. If this router isn't listening, it's not set up to manage the history.

If you want to replace the url before you have a router managing the history, then you can directly call `history.replaceState`.

I'll keep this issue open, since instead of the current behavior, it should throw a more helpful error whenever you try to navigate with a router that isn't managing the history.
